#
# Copyright 2014 Ettus Research LLC
# Copyright 2016 Ettus Research, a National Instruments Company
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

##################################################
# radio library
##################################################
RADIO_200_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/radio_200/, \
./radio_legacy.v \
./fsk_demod.v \
./pocsag_bitsync.v \
./pocsag_framer.v \
./pocsag_channel_filter.v \
./clip_detect.v \
./channel_width_detect.v \
./gsc_framer.v \
))
